# Generated by Django 5.1 on 2024-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPersonalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserPredictModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Age", models.IntegerField()),
                ("Gender", models.CharField(max_length=100)),
                ("Smoking", models.FloatField()),
                ("Hx_Smoking", models.FloatField()),
                ("Hx_Radiothreapy", models.FloatField()),
                ("Thyroid_Function", models.FloatField()),
                ("Physical_Examination", models.FloatField()),
                ("Adenopathy", models.FloatField()),
                ("Pathology", models.FloatField()),
                ("Focality", models.FloatField()),
                ("Stage", models.CharField(max_length=100)),
                ("Response", models.FloatField()),
                ("Recurred", models.FloatField()),
            ],
        ),
    ]
